### ISSUE TITLE
Checklist for unfinished Chinise docs

### ISSUE THREAD

**Issue by nbei** [open-mmlab/mmgeneration#66]
The following Chinese docs have not been finished:

- [ ] Change log in [docs_zh-CN/changelog.md](https://github.com/open-mmlab/mmgeneration/blob/master/docs_zh-CN/changelog.md) 
- [ ] Quick run in [docs_zh-CN/quick_run.md](https://github.com/open-mmlab/mmgeneration/blob/master/docs_zh-CN/quick_run.md)
- [ ] get started in [docs_zh-CN/get_started.md](https://github.com/open-mmlab/mmgeneration/blob/master/docs_zh-CN/get_started.md)
- [ ] application tutorial in [docs_zh-CN/tutorials/applications.md](https://github.com/open-mmlab/mmgeneration/blob/master/docs_zh-CN/tutorials/applications.md)
- [ ] config tutorial in [docs_zh-CN/tutorials/config.md](https://github.com/open-mmlab/mmgeneration/blob/master/docs_zh-CN/tutorials/config.md)
- [ ] customize dataset tutorial in [docs_zh-CN/tutorials/customize_dataset.md](https://github.com/open-mmlab/mmgeneration/blob/master/docs_zh-CN/tutorials/customize_dataset.md)
- [ ] customize loss tutorial in [docs_zh-CN/tutorials/customize_losses.md](https://github.com/open-mmlab/mmgeneration/blob/master/docs_zh-CN/tutorials/customize_losses.md)
- [ ] customize model tutorial in [docs_zh-CN/tutorials/customize_models.md](https://github.com/open-mmlab/mmgeneration/blob/master/docs_zh-CN/tutorials/customize_models.md)
- [ ] customize runtime tutorial in [docs_zh-CN/tutorials/customize_runtime.md](https://github.com/open-mmlab/mmgeneration/blob/master/docs_zh-CN/tutorials/customize_runtime.md)
- [ ] ddp train tutorial in [docs_zh-CN/tutorials/ddp_train_gans.md](https://github.com/open-mmlab/mmgeneration/blob/master/docs_zh-CN/tutorials/ddp_train_gans.md)

**Comment by plyfager** [comment]
Maybe we should start doing these items.
